### ISSUE TITLE
Some issues since moving to interactive-cpp v2

### ISSUE THREAD

**Issue by GSQMick** [mixer/interactive-unreal-plugin#39]
I tested the plugin when it was still using interactive-cpp v1 by default, and it was working great for the most part, with some exception like the Textbox events not working. 
Upgrading to this new version, I now have crash when trying to "Capture Spark Transaction" and it looks like it could be due to the Spark Transaction Id being empty.
Also, some general events like "Participant Joined" do not work anymore.
I tested the Textbox events and they seem to work, so this is nice. However, same problem with them : Transaction Id is empty. I also notices that the Spark Cost parameter seems to be pointing to invalid memory...
I also needed to had some missing include for the project to compile in Development config. I t was however compiling correctly in Development Editor. 
Any idea what could be wrong?

**Comment by LongSteve** [comment]
Did you ever resolve this?  I've just added capturing the spark transaction value, and I get a crash at line 826 of interactive_session.cpp with what appears to be an empty transaction id.

**Comment by LongSteve** [comment]
Thanks for the reply.  I'm stepping through the source in Visual Studio, and it looks like thr TransactionId passed in from the button event is **Empty**, which might be due to me using a test account with a Sandbox.  I'm going to put in some guards to not capture an empty transaction, and then see if I can test with a real user outside the sandbox.  I'll let you know if anything concrete shows up.
